# Generated by Django 2.0 on 2018-03-04 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNum', models.CharField(max_length=15, unique=True, verbose_name='课程编号')),
                ('Name', models.CharField(max_length=15, verbose_name='课程名')),
                ('Type', models.IntegerField(choices=[(0, '室内'), (1, '练习'), (2, '视屏')], verbose_name='课程类型')),
                ('Class', models.PositiveSmallIntegerField(default=20, verbose_name='类')),
                ('Note', models.CharField(blank=True, max_length=200, verbose_name='课程描述')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNum', models.CharField(max_length=15, unique=True, verbose_name='班级编号')),
                ('Name', models.CharField(max_length=15, verbose_name='班级名')),
                ('LimitNum', models.PositiveSmallIntegerField(default=50, verbose_name='最大人数')),
                ('Note', models.CharField(blank=True, max_length=200, verbose_name='班级描述')),
                ('hasAllocNum', models.PositiveSmallIntegerField(default=0, verbose_name='已分配数')),
                ('Courses', models.ManyToManyField(blank=True, to='tm.Course', verbose_name='基础课程')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNum', models.CharField(max_length=15, unique=True, verbose_name='材料编号')),
                ('Name', models.CharField(max_length=15, verbose_name='材料名')),
                ('Type', models.IntegerField(choices=[(0, '书'), (1, '工作簿'), (2, '实验器材'), (3, '其他')], verbose_name='材料类型')),
                ('InventoryLimitNum', models.PositiveSmallIntegerField(default=50, verbose_name='最大库存')),
                ('InventoryNum', models.PositiveSmallIntegerField(default=0, verbose_name='库存数量')),
                ('Price', models.PositiveSmallIntegerField(verbose_name='价格')),
                ('Note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '材料',
                'verbose_name_plural': '材料',
            },
        ),
        migrations.CreateModel(
            name='MaterialAllocModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num', models.PositiveSmallIntegerField(verbose_name='数量')),
                ('Data', models.DateTimeField(auto_now_add=True, verbose_name='日期时间')),
                ('Note', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tm.Grade', verbose_name='班级')),
                ('Material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tm.Material', verbose_name='材料')),
            ],
            options={
                'verbose_name': '材料分配记录',
                'verbose_name_plural': '材料分配记录',
            },
        ),
        migrations.CreateModel(
            name='MaterialStorageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num', models.PositiveSmallIntegerField(verbose_name='数量')),
                ('Data', models.DateTimeField(auto_now_add=True, verbose_name='日期时间')),
                ('Note', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('Material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tm.Material', verbose_name='材料')),
            ],
            options={
                'verbose_name': '材料入库记录',
                'verbose_name_plural': '材料入库记录',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15, verbose_name='姓名')),
                ('SerialNum', models.CharField(max_length=10, unique=True, verbose_name='学号')),
                ('Gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, '女性'), (1, '男性')], null=True, verbose_name='性别')),
                ('Age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('Tel', models.CharField(blank=True, max_length=13, null=True, verbose_name='电话号码')),
                ('Note', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('ElectiveCourses', models.ManyToManyField(to='tm.Course', verbose_name='选修课')),
                ('Grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tm.Grade', verbose_name='班级')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='Materials',
            field=models.ManyToManyField(blank=True, to='tm.Material', verbose_name='教学材料'),
        ),
    ]
