# Generated by Django 2.0.1 on 2018-01-03 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNum', models.CharField(max_length=15, unique=True, verbose_name='CourseId')),
                ('Name', models.CharField(max_length=15, verbose_name='CourseName')),
                ('Type', models.IntegerField(choices=[(0, 'ClassRoom'), (1, 'Practice'), (2, 'Video')], verbose_name='Course Type')),
                ('Class', models.PositiveSmallIntegerField(default=20, verbose_name='Class')),
                ('Note', models.CharField(blank=True, max_length=200, verbose_name='Course Description')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNum', models.CharField(max_length=15, unique=True, verbose_name='GradeId')),
                ('Name', models.CharField(max_length=15, verbose_name='GradeName')),
                ('LimitNum', models.PositiveSmallIntegerField(default=50, verbose_name='MaxNum')),
                ('Note', models.CharField(blank=True, max_length=200, verbose_name='Grade Description')),
                ('Courses', models.ManyToManyField(blank=True, to='tm.Course', verbose_name='Base Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNum', models.CharField(max_length=15, unique=True, verbose_name='MaterialId')),
                ('Name', models.CharField(max_length=15, verbose_name='MaterialName')),
                ('Type', models.IntegerField(choices=[(0, 'Book'), (1, 'WorkBook'), (2, 'ExperimentEquipMent'), (3, 'Other')], verbose_name='MaterialType')),
                ('InventoryLimitNum', models.PositiveSmallIntegerField(default=50, verbose_name='InventoryLimit')),
                ('InventoryNum', models.PositiveSmallIntegerField(default=0, verbose_name='InventoryNum')),
                ('Price', models.PositiveSmallIntegerField(blank=True, verbose_name='Price')),
                ('Note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15, verbose_name='Name')),
                ('SerialNum', models.CharField(max_length=10, unique=True, verbose_name='StudentId')),
                ('Gender', models.PositiveSmallIntegerField(choices=[(0, 'female'), (1, 'male')], verbose_name='Gender')),
                ('Age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('Email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('Tel', models.CharField(blank=True, max_length=13, verbose_name='Telephone Number')),
                ('Note', models.CharField(max_length=200, verbose_name='note')),
                ('ElectiveCourses', models.ManyToManyField(to='tm.Course', verbose_name='Elective Courses')),
                ('Grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tm.Grade', verbose_name='Grade')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Materials',
            field=models.ManyToManyField(blank=True, to='tm.Material', verbose_name='Teach Materilas'),
        ),
    ]
