# Generated by Django 2.0 on 2018-03-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialallocmodel',
            name='Grade',
        ),
        migrations.AddField(
            model_name='materialallocmodel',
            name='GradeName',
            field=models.CharField(default='-', max_length=200, verbose_name='班级'),
        ),
    ]
