# Generated by Django 2.0 on 2018-02-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialAlloc',
            new_name='MaterialAllocModel',
        ),
        migrations.AlterField(
            model_name='material',
            name='Price',
            field=models.PositiveSmallIntegerField(verbose_name='Price'),
        ),
    ]
