# Generated by Django 2.0 on 2018-04-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0002_auto_20180304_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='isAlloc',
            field=models.BooleanField(default=False, verbose_name='是否分配'),
        ),
    ]
