# Generated by Django 2.0 on 2018-04-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0003_studentinfo_isalloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='AllocMaterial',
            field=models.ManyToManyField(blank=True, to='tm.Material', verbose_name='已分配的材料'),
        ),
    ]
