# Generated by Django 2.0.1 on 2018-01-03 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15, verbose_name='Name')),
                ('SerialNum', models.CharField(max_length=10, unique=True, verbose_name='StudentId')),
                ('Gender', models.IntegerField(choices=[(0, 'female'), (1, 'male')], verbose_name='Gender')),
                ('Age', models.IntegerField(verbose_name='Age')),
                ('Note', models.CharField(max_length=200, verbose_name='note')),
                ('ElectiveCourses', models.ManyToManyField(to='tm.Course', verbose_name='Elective Courses')),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=10, verbose_name='password')),
                ('studentInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sim.StudentInfo', to_field='SerialNum')),
            ],
        ),
    ]
