# Generated by Django 2.0 on 2018-01-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNum', models.CharField(max_length=15, verbose_name='StudentId')),
                ('Password', models.CharField(max_length=15, verbose_name='Password')),
                ('studentInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tm.StudentInfo', to_field='SerialNum')),
            ],
        ),
    ]
